# **Car Price Prediction**
using Gradient Boosting Regressor

### **Importing Libraries and Dataset**

In [51]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
df = pd.read_csv("CarPrice_Assignment.csv")
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

### **Data Pre-Prcessing**

In [53]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [54]:
df.shape

(205, 26)

In [55]:
df.drop("car_ID",axis=1,inplace=True)
df.drop("CarName",axis=1,inplace=True)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   fueltype          205 non-null    object
 2   aspiration        205 non-null    object
 3   doornumber        205 non-null    object
 4   carbody           205 non-null    object
 5   drivewheel        205 non-null    object
 6   enginelocation    205 non-null    object
 7   wheelbase         205 non-null    float64
 8   carlength         205 non-null    float64
 9   carwidth          205 non-null    float64
 10  carheight         205 non-null    float64
 11  curbweight        205 non-null    int64
 12  enginetype        205 non-null    object
 13  cylindernumber    205 non-null    object
 14  enginesize        205 non-null    int64
 15  fuelsystem        205 non-null    object
 16  boreratio         205 non-null    float64
 17  stroke            205 non-null    float64
 18  compressionratio  205 non-null    float64
 19  horsepower        205 non-null    int64
 20  peakrpm           205 non-null    int64
 21  citympg           205 non-null    int64
 22  highwaympg        205 non-null    int64
 23  price             205 non-null    float64
dtypes: float64(8), int64(7), object(9)
memory usage: 38.6+ KB

In [58]:
df.corr()['price']

<ipython-input-58-cbe57b8e6d9c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()['price']

symboling          -0.079978
wheelbase           0.577816
carlength           0.682920
carwidth            0.759325
carheight           0.119336
curbweight          0.835305
enginesize          0.874145
boreratio           0.553173
stroke              0.079443
compressionratio    0.067984
horsepower          0.808139
peakrpm            -0.085267
citympg            -0.685751
highwaympg         -0.697599
price               1.000000
Name: price, dtype: float64

In [59]:
from pandas.core.arrays.sparse import dtype
str_col=[]
int_col=[]
for i in df.columns:
  # print(i)
  if(df[i].dtype!="object"):
    int_col.append(i)
  if(df[i].dtype=="object"):
    str_col.append(i)

In [60]:
int_col

['symboling',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginesize',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [61]:
str_col

['fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'enginetype',
 'cylindernumber',
 'fuelsystem']

In [62]:
removed=[]
for i in int_col:
  if(df[i].corr(df.price)<0.2 and df[i].corr(df.price)>-0.2):
    del df[i]
    removed.append(i)

In [64]:
removed

['symboling', 'carheight', 'stroke', 'compressionratio', 'peakrpm']

In [66]:
df.shape

(205, 19)

In [67]:
for i in str_col:
  print(df[i].value_counts())

gas       185
diesel     20
Name: fueltype, dtype: int64
std      168
turbo     37
Name: aspiration, dtype: int64
four    115
two      90
Name: doornumber, dtype: int64
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64
fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64
front    202
rear       3
Name: enginelocation, dtype: int64
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: enginetype, dtype: int64
four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: cylindernumber, dtype: int64
mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64

In [68]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in str_col:
  df[i]=le.fit_transform(df[i])

In [69]:
df.head()

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,horsepower,citympg,highwaympg,price
0,1,0,1,0,2,0,88.6,168.8,64.1,2548,0,2,130,5,3.47,111,21,27,13495.0
1,1,0,1,0,2,0,88.6,168.8,64.1,2548,0,2,130,5,3.47,111,21,27,16500.0
2,1,0,1,2,2,0,94.5,171.2,65.5,2823,5,3,152,5,2.68,154,19,26,16500.0
3,1,0,0,3,1,0,99.8,176.6,66.2,2337,3,2,109,5,3.19,102,24,30,13950.0
4,1,0,0,3,0,0,99.4,176.6,66.4,2824,3,1,136,5,3.19,115,18,22,17450.0

In [70]:
df.shape

(205, 19)

### **Splitting the Data, Traning and Predicting it using Gradientboosting Regressor algorithm**

In [71]:
X = df.drop('price',axis=1)
y=df['price']

In [72]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

In [73]:
train_X, test_X, train_y, test_y = train_test_split(X, y,
                                                    test_size = 0.25,
                                                    random_state = 23)
gbr = GradientBoostingRegressor(loss='absolute_error',
                                learning_rate=0.1,
                                n_estimators=300,
                                max_depth = 1,
                                random_state = 23,
                                max_features = 5)

gbr.fit(train_X, train_y)
pred_y = gbr.predict(test_X)
test_rmse = mean_squared_error(test_y, pred_y) ** (1 / 2)
print('Root mean Square error: {:.2f}'.format(test_rmse))

Root mean Square error: 2799.37

### **Metrics**

In [74]:
print('R Square value : ', r2_score(test_y,pred_y))

R Square value :  0.9127158096726634